// TEST_DB — 5 Full Tests (25 Questions each)
const TEST_DB = [
    {
        id: 1,
        title: "TEST 1: GENERAL PROFICIENCY",
        description: "Tổng hợp kiến thức cơ bản về dịch vụ và an toàn (Theo tài liệu gốc).",
        timeLimit: 25 * 60,
        questions: [
            { id: 1, sectionTitle: "PART 1 – SENTENCE COMPLETION", question: "I'm sorry, but this seat is ______ for passengers with reduced mobility.", options: ["A. blocked", "B. reserved", "C. prevented", "D. saved"], correctIndex: 1, explanation: "'Reserved' (đã đặt trước/dành riêng) là từ dùng để chỉ chỗ ngồi được giữ cho đối tượng cụ thể." },
            { id: 2, question: "Please place your carry-on luggage in the ______ compartment above your seat.", options: ["A. baggage", "B. overhead", "C. upper", "D. storage"], correctIndex: 1, explanation: "'Overhead compartment' là thuật ngữ hàng không chỉ ngăn đựng hành lý phía trên đầu." },
            { id: 3, question: "Smoking is strictly prohibited on board, including in the ______.", options: ["A. kitchen", "B. restroom", "C. lavatory", "D. corridor"], correctIndex: 2, explanation: "Trong hàng không, nhà vệ sinh trên máy bay được gọi chuyên môn là 'lavatory'." },
            { id: 4, question: "This suitcase exceeds the weight limit, so an ______ baggage fee will apply.", options: ["A. excess", "B. extra", "C. overweight", "D. additional"], correctIndex: 2, explanation: "Overweight baggage fee (phí hành lý quá cân)." },
            { id: 5, question: "Cabin crew must remain ______ and professional when handling difficult passengers.", options: ["A. nervous", "B. calm", "C. sensitive", "D. emotional"], correctIndex: 1, explanation: "Giữ bình tĩnh (calm) là phẩm chất quan trọng." },
            { id: 6, question: "May I ask you to fasten your seatbelt as we are preparing for ______?", options: ["A. landing", "B. arrival", "C. touchdown", "D. descent"], correctIndex: 0, explanation: "Preparing for landing (chuẩn bị hạ cánh)." },
            { id: 7, question: "For safety reasons, electronic devices must be switched to ______ mode.", options: ["A. silent", "B. safe", "C. airplane", "D. offline"], correctIndex: 2, explanation: "Airplane mode (chế độ máy bay)." },
            { id: 8, question: "The passenger was removed from the aircraft for carrying ______ items in his bag.", options: ["A. dangerous", "B. restricted", "C. limited", "D. special"], correctIndex: 1, explanation: "Restricted items (các vật phẩm bị hạn chế/cấm)." },
            { id: 9, question: "This flight offers a wide range of complimentary food and ______.", options: ["A. meals", "B. snacks", "C. beverages", "D. dishes"], correctIndex: 2, explanation: "Food and beverages (Đồ ăn và thức uống)." },
            { id: 10, question: "The restroom is currently occupied, but it will be ______ shortly.", options: ["A. empty", "B. vacant", "C. free", "D. unused"], correctIndex: 1, explanation: "Vacant (trống/có thể sử dụng)." },
            { id: 11, sectionTitle: "PART 2 – READING COMPREHENSION", passageTitle: "Passage 1", passageContent: "Emirates operates flights to more than 150 destinations worldwide. Safety is the airline's top priority.", question: "How many destinations does Emirates operate flights to?", options: ["A. Around 100", "B. Exactly 150", "C. Over 150", "D. Less than 150"], correctIndex: 2, explanation: "More than 150 destinations." },
            { id: 12, passageTitle: "Passage 1", passageContent: "Passengers are required to follow cabin crew instructions at all times, especially during takeoff and landing.", question: "When must passengers strictly follow cabin crew instructions?", options: ["A. Only during boarding", "B. At all times", "C. Only in emergencies", "D. During meals"], correctIndex: 1, explanation: "At all times." },
            { id: 13, passageTitle: "Passage 1", passageContent: "Carry-on baggage must be properly stored in overhead compartments or under the seat in front of you.", question: "Where should carry-on baggage be stored?", options: ["A. On the floor", "B. In the aisle", "C. In overhead compartments or under seats", "D. Anywhere convenient"], correctIndex: 2, explanation: "Overhead compartments or under seats." },
            { id: 14, passageTitle: "Passage 2", passageContent: "Cabin crew are responsible for ensuring passenger comfort while maintaining strict safety standards.", question: "What is one key responsibility of cabin crew?", options: ["A. Selling tickets", "B. Ensuring passenger comfort and safety", "C. Flying the aircraft", "D. Managing luggage fees"], correctIndex: 1, explanation: "Ensuring passenger comfort and safety." },
            { id: 15, passageTitle: "Passage 2", passageContent: "They must communicate clearly, remain calm under pressure, and work effectively as part of a multicultural team.", question: "Which quality is especially important when working under pressure?", options: ["A. Creativity", "B. Speed", "C. Calmness", "D. Authority"], correctIndex: 2, explanation: "Calmness (Remain calm)." },
            { id: 16, sectionTitle: "PART 3 – GRAMMAR & VOCABULARY", question: "The aircraft is currently ______ maintenance.", options: ["A. on", "B. under", "C. in", "D. at"], correctIndex: 1, explanation: "Under maintenance (đang bảo trì)." },
            { id: 17, question: "Passengers are advised to arrive at the airport ______ advance.", options: ["A. on", "B. with", "C. in", "D. at"], correctIndex: 2, explanation: "In advance (trước)." },
            { id: 18, question: "Choose the correct synonym for \u201cprohibited.\u201d", options: ["A. Optional", "B. Allowed", "C. Forbidden", "D. Recommended"], correctIndex: 2, explanation: "Prohibited = Forbidden (Cấm)." },
            { id: 19, question: "Cabin crew must be able to communicate ______ with passengers.", options: ["A. effective", "B. effect", "C. effectiveness", "D. effectively"], correctIndex: 3, explanation: "Effectively (trạng từ)." },
            { id: 20, question: "If a passenger feels unwell, the cabin crew should ______ assistance immediately.", options: ["A. offer", "B. give", "C. take", "D. do"], correctIndex: 0, explanation: "Offer assistance (đề nghị giúp đỡ)." },
            { id: 21, sectionTitle: "PART 4 – CONTEXTUAL VOCABULARY", question: "Please remain seated until the seatbelt sign has been ______.", options: ["A. switched on", "B. turned off", "C. broken", "D. removed"], correctIndex: 1, explanation: "Turned off (đèn hiệu tắt)." },
            { id: 22, question: "Long-haul flights require cabin crew to manage ______ and fatigue effectively.", options: ["A. stress", "B. pressure", "C. tired", "D. difficulty"], correctIndex: 0, explanation: "Manage stress (quản lý căng thẳng)." },
            { id: 23, question: "A professional cabin crew member always maintains a ______ appearance.", options: ["A. neat", "B. tidy", "C. polished", "D. All are correct"], correctIndex: 3, explanation: "Neat, tidy, polished đều đúng." },
            { id: 24, question: "Passengers should store personal items ______ the seat in front of them.", options: ["A. below", "B. under", "C. beneath", "D. All are correct"], correctIndex: 3, explanation: "Below/Under/Beneath (bên dưới)." },
            { id: 25, question: "Clear communication helps prevent misunderstandings and ensures ______ service.", options: ["A. smooth", "B. smoothness", "C. smoothly", "D. smoothing"], correctIndex: 0, explanation: "Smooth service (dịch vụ trôi chảy/suôn sẻ)." }
        ]
    },
    {
        id: 2,
        title: "TEST 2: PRE-FLIGHT & BOARDING",
        description: "Tập trung vào từ vựng đón khách, xếp chỗ, hành lý và thủ tục sân bay.",
        timeLimit: 25 * 60,
        questions: [
            { id: 1, sectionTitle: "PART 1 – SENTENCE COMPLETION", question: "May I see your ______ pass, please?", options: ["A. boarding", "B. board", "C. flight", "D. entry"], correctIndex: 0, explanation: "'Boarding pass' (thẻ lên máy bay)." },
            { id: 2, question: "Please fasten your ______ and ensure your seat back is upright.", options: ["A. chair", "B. seatbelt", "C. strap", "D. buckle"], correctIndex: 1, explanation: "'Seatbelt' (dây an toàn)." },
            { id: 3, question: "We are currently waiting for clearance from ______ control before takeoff.", options: ["A. ground", "B. air", "C. traffic", "D. tower"], correctIndex: 0, explanation: "'Ground control' (kiểm soát mặt đất)." },
            { id: 4, question: "Passengers seated in the ______ exit row must be willing to assist in an emergency.", options: ["A. danger", "B. safety", "C. emergency", "D. urgent"], correctIndex: 2, explanation: "'Emergency exit row' (hàng ghế thoát hiểm)." },
            { id: 5, question: "The flight has been ______ due to bad weather conditions.", options: ["A. delayed", "B. late", "C. stopped", "D. slow"], correctIndex: 0, explanation: "Delayed (bị hoãn)." },
            { id: 6, question: "Please ______ your bags under the seat in front of you.", options: ["A. put", "B. stow", "C. keep", "D. hold"], correctIndex: 1, explanation: "'Stow' là từ chuyên ngành chỉ việc cất gọn hành lý." },
            { id: 7, question: "All passengers must go through security ______ before entering the departure lounge.", options: ["A. checking", "B. check", "C. control", "D. inspection"], correctIndex: 1, explanation: "Security check (kiểm tra an ninh)." },
            { id: 8, question: "Could you please place your tray table in the ______ position?", options: ["A. up", "B. upright", "C. straight", "D. vertical"], correctIndex: 1, explanation: "Upright position (vị trí thẳng đứng)." },
            { id: 9, question: "We apologize for the delay and thank you for your ______.", options: ["A. patient", "B. patience", "C. patiently", "D. waiting"], correctIndex: 1, explanation: "Thank you for your patience (sự kiên nhẫn)." },
            { id: 10, question: "Priority boarding is available for passengers travelling in ______ Class.", options: ["A. Business", "B. Busy", "C. High", "D. Top"], correctIndex: 0, explanation: "Business Class (Hạng thương gia)." },
            { id: 11, sectionTitle: "PART 2 – READING COMPREHENSION", passageTitle: "Baggage Policy", passageContent: "Passengers are allowed one carry-on bag not exceeding 7kg. Laptop bags must be placed inside the carry-on or stored separately under the seat.", question: "What is the weight limit for carry-on bags?", options: ["A. 10kg", "B. 5kg", "C. 7kg", "D. 15kg"], correctIndex: 2, explanation: "Not exceeding 7kg." },
            { id: 12, passageTitle: "Baggage Policy", passageContent: "Any liquids over 100ml must be packed in checked luggage. Exceptions are made for baby food and essential medicines.", question: "Which items are exempt from the liquid rule?", options: ["A. Water bottles", "B. Perfumes", "C. Baby food and medicine", "D. Shampoo"], correctIndex: 2, explanation: "Baby food and essential medicines." },
            { id: 13, passageTitle: "Boarding Gate", passageContent: "Gate 12 is now closed. Passengers for flight EK394 to Dubai please proceed immediately to Gate 25.", question: "What has happened to Gate 12?", options: ["A. It is open", "B. It is boarding", "C. It is closed", "D. It is broken"], correctIndex: 2, explanation: "Gate 12 is now closed." },
            { id: 14, passageTitle: "Boarding Gate", passageContent: "Gate 12 is now closed. Passengers for flight EK394 to Dubai please proceed immediately to Gate 25.", question: "Where should passengers go now?", options: ["A. Gate 12", "B. Gate 25", "C. Check-in counter", "D. Duty free"], correctIndex: 1, explanation: "Proceed immediately to Gate 25." },
            { id: 15, passageTitle: "Check-in", passageContent: "Please have your passport and visa ready for document verification.", question: "What documents are required?", options: ["A. ID only", "B. Passport and visa", "C. Ticket only", "D. Credit card"], correctIndex: 1, explanation: "Passport and visa." },
            { id: 16, sectionTitle: "PART 3 – GRAMMAR", question: "The flight ______ due to depart at 08:00 AM.", options: ["A. is", "B. are", "C. will", "D. has"], correctIndex: 0, explanation: "Is due to (dự kiến sẽ)." },
            { id: 17, question: "Would you mind ______ seats with this family?", options: ["A. switch", "B. to switch", "C. switching", "D. switched"], correctIndex: 2, explanation: "Mind + V-ing (switching)." },
            { id: 18, question: "I look forward ______ you on board again soon.", options: ["A. to seeing", "B. to see", "C. seeing", "D. see"], correctIndex: 0, explanation: "Look forward to + V-ing." },
            { id: 19, question: "Neither the pilot ______ the co-pilot was available.", options: ["A. or", "B. nor", "C. and", "D. but"], correctIndex: 1, explanation: "Neither... nor..." },
            { id: 20, question: "The luggage ______ weighed by the ground staff right now.", options: ["A. is being", "B. is been", "C. has being", "D. was being"], correctIndex: 0, explanation: "Is being weighed (bị động thì hiện tại tiếp diễn)." },
            { id: 21, sectionTitle: "PART 4 – VOCABULARY", question: "We apologize for the ______ caused by the late arrival.", options: ["A. convenience", "B. inconvenience", "C. comfort", "D. happy"], correctIndex: 1, explanation: "Inconvenience (sự bất tiện)." },
            { id: 22, question: "Please ensure your phone is switched off or in flight ______.", options: ["A. mood", "B. mode", "C. model", "D. way"], correctIndex: 1, explanation: "Flight mode." },
            { id: 23, question: "The ______ time is 14 hours and 30 minutes.", options: ["A. fly", "B. flight", "C. flying", "D. flown"], correctIndex: 2, explanation: "Flying time (thời gian bay)." },
            { id: 24, question: "There is a ______ of 2 hours in Singapore.", options: ["A. stopover", "B. stop", "C. stopping", "D. stopped"], correctIndex: 0, explanation: "Stopover (điểm dừng chân)." },
            { id: 25, question: "Please show your bag tag to the ______ agent.", options: ["A. gate", "B. door", "C. entry", "D. way"], correctIndex: 0, explanation: "Gate agent (nhân viên cửa khởi hành)." }
        ]
    },
    {
        id: 3,
        title: "TEST 3: IN-FLIGHT SERVICE (F&B)",
        description: "Chủ đề phục vụ ăn uống, xử lý yêu cầu khách hàng và Duty Free.",
        timeLimit: 25 * 60,
        questions: [
            { id: 1, sectionTitle: "PART 1 – SENTENCE COMPLETION", question: "Would you like chicken or beef for your ______ meal?", options: ["A. main", "B. primary", "C. first", "D. major"], correctIndex: 0, explanation: "'Main meal' (món chính)." },
            { id: 2, question: "I'm afraid we have run ______ of the vegetarian option.", options: ["A. away", "B. off", "C. out", "D. over"], correctIndex: 2, explanation: "Run out of (hết sạch)." },
            { id: 3, question: "Complimentary ______ are available throughout the flight.", options: ["A. foods", "B. beverages", "C. drink", "D. eating"], correctIndex: 1, explanation: "Beverages (đồ uống)." },
            { id: 4, question: "Could I have a ______? I feel a bit cold.", options: ["A. towel", "B. blanket", "C. pillow", "D. sheet"], correctIndex: 1, explanation: "Blanket (chăn)." },
            { id: 5, question: "Please keep the aisle ______ for the trolleys.", options: ["A. clear", "B. clean", "C. empty", "D. open"], correctIndex: 0, explanation: "Keep the aisle clear (giữ lối đi thông thoáng)." },
            { id: 6, question: "Here is a wet ______ for you to freshen up.", options: ["A. paper", "B. tissue", "C. wipe", "D. cloth"], correctIndex: 2, explanation: "Wet wipe (khăn ướt)." },
            { id: 7, question: "Do you have any ______ to nuts or dairy products?", options: ["A. allergic", "B. allergies", "C. allergens", "D. allergy"], correctIndex: 1, explanation: "Have allergies (bị dị ứng)." },
            { id: 8, question: "Would you like some ice and ______ with your drink?", options: ["A. lemon", "B. sour", "C. fruit", "D. sweet"], correctIndex: 0, explanation: "Ice and lemon (đá và chanh)." },
            { id: 9, question: "I will return to ______ your tray shortly.", options: ["A. collect", "B. pick", "C. take", "D. get"], correctIndex: 0, explanation: "Collect your tray (thu dọn khay ăn)." },
            { id: 10, question: "This perfume is available in our ______ catalog.", options: ["A. duty-free", "B. tax-free", "C. free-tax", "D. no-tax"], correctIndex: 0, explanation: "Duty-free catalog." },
            { id: 11, sectionTitle: "PART 2 – READING COMPREHENSION", passageTitle: "Special Meals", passageContent: "Passengers with specific dietary requirements must request special meals at least 24 hours before departure.", question: "When should special meals be ordered?", options: ["A. On board", "B. At check-in", "C. 24 hours before departure", "D. After landing"], correctIndex: 2, explanation: "24 hours before departure." },
            { id: 12, passageTitle: "Special Meals", passageContent: "We cannot guarantee availability if requested on board. Kosher and Halal meals are available on all routes.", question: "Are Kosher meals available?", options: ["A. No", "B. Yes, on all routes", "C. Only on some routes", "D. Only for business class"], correctIndex: 1, explanation: "Yes, on all routes." },
            { id: 13, passageTitle: "Alcohol Policy", passageContent: "Cabin crew have the right to refuse alcohol service to any passenger who appears intoxicated.", question: "Can cabin crew refuse alcohol?", options: ["A. No, never", "B. Yes, if passenger is intoxicated", "C. Only to minors", "D. Only during landing"], correctIndex: 1, explanation: "Yes, if passenger appears intoxicated." },
            { id: 14, passageTitle: "Duty Free", passageContent: "We accept major credit cards and cash in US Dollars, Euros, and Dirhams. Change will be given in Dirhams only.", question: "What currency is change given in?", options: ["A. USD", "B. Euros", "C. Dirhams", "D. Passenger's choice"], correctIndex: 2, explanation: "Change will be given in Dirhams only." },
            { id: 15, passageTitle: "Duty Free", passageContent: "Please note that liquids purchased in duty-free must be kept in a sealed security bag.", question: "How must duty-free liquids be kept?", options: ["A. Open box", "B. Sealed security bag", "C. Plastic bag", "D. Pocket"], correctIndex: 1, explanation: "Sealed security bag." },
            { id: 16, sectionTitle: "PART 3 – GRAMMAR", question: "This duty-free catalog offers a wide ______ of perfumes.", options: ["A. select", "B. selection", "C. selective", "D. selecting"], correctIndex: 1, explanation: "A wide selection (danh từ)." },
            { id: 17, question: "You ______ drink too much alcohol on high altitude.", options: ["A. shouldn't", "B. don't", "C. won't", "D. can't"], correctIndex: 0, explanation: "Shouldn't (khuyên không nên)." },
            { id: 18, question: "If you need anything, please ______ the call button.", options: ["A. press", "B. to press", "C. pressing", "D. pressed"], correctIndex: 0, explanation: "Imperative sentence (câu mệnh lệnh): Press." },
            { id: 19, question: "The coffee is ______ hot, please be careful.", options: ["A. very", "B. too", "C. enough", "D. much"], correctIndex: 0, explanation: "Very hot (rất nóng)." },
            { id: 20, question: "Would you like me ______ that for you?", options: ["A. refill", "B. to refill", "C. refilling", "D. refilled"], correctIndex: 1, explanation: "Would you like me to + V." },
            { id: 21, sectionTitle: "PART 4 – VOCABULARY", question: "I can offer you a full ______ if the item is damaged.", options: ["A. fund", "B. refund", "C. return", "D. pay"], correctIndex: 1, explanation: "Refund (hoàn tiền)." },
            { id: 22, question: "Please lower the ______ blind if the sun is too strong.", options: ["A. window", "B. glass", "C. pane", "D. view"], correctIndex: 0, explanation: "Window blind (tấm che cửa sổ)." },
            { id: 23, question: "We serve breakfast, lunch, and ______ on this flight.", options: ["A. dinner", "B. diner", "C. dining", "D. dine"], correctIndex: 0, explanation: "Dinner (bữa tối)." },
            { id: 24, question: "Is your meal to your ______?", options: ["A. satisfy", "B. satisfaction", "C. satisfying", "D. satisfied"], correctIndex: 1, explanation: "To your satisfaction (vừa ý)." },
            { id: 25, question: "This headset is for your ______ entertainment.", options: ["A. in-flight", "B. on-flight", "C. at-flight", "D. by-flight"], correctIndex: 0, explanation: "In-flight entertainment (giải trí trên chuyến bay)." }
        ]
    },
    {
        id: 4,
        title: "TEST 4: SAFETY & MEDICAL EMERGENCIES",
        description: "Từ vựng về sơ cấp cứu, thiết bị an toàn và tình huống khẩn cấp.",
        timeLimit: 25 * 60,
        questions: [
            { id: 1, sectionTitle: "PART 1 – SENTENCE COMPLETION", question: "In the unlikely event of a sudden loss of cabin pressure, oxygen masks will ______ drop.", options: ["A. automatic", "B. automated", "C. automatically", "D. automation"], correctIndex: 2, explanation: "Automatically (trạng từ)." },
            { id: 2, question: "Please put on your own mask before ______ others.", options: ["A. help", "B. helping", "C. to help", "D. helped"], correctIndex: 1, explanation: "Before helping." },
            { id: 3, question: "The life ______ is located under your seat.", options: ["A. jacket", "B. coat", "C. vest", "D. boat"], correctIndex: 2, explanation: "Life vest (áo phao)." },
            { id: 4, question: "We need to ______ the aircraft immediately due to smoke.", options: ["A. empty", "B. leave", "C. evacuate", "D. abandon"], correctIndex: 2, explanation: "Evacuate (sơ tán)." },
            { id: 5, question: "The passenger is suffering from severe ______ sickness.", options: ["A. air", "B. motion", "C. flight", "D. travel"], correctIndex: 1, explanation: "Motion sickness (say tàu xe)." },
            { id: 6, question: "Please remain ______ and follow the crew's instructions.", options: ["A. calm", "B. quiet", "C. still", "D. silent"], correctIndex: 0, explanation: "Remain calm (giữ bình tĩnh)." },
            { id: 7, question: "The fire extinguisher is ______ in the overhead bin.", options: ["A. put", "B. located", "C. stayed", "D. set"], correctIndex: 1, explanation: "Located (được đặt tại)." },
            { id: 8, question: "He felt ______ and asked for a glass of water.", options: ["A. dizzy", "B. pain", "C. hurt", "D. injury"], correctIndex: 0, explanation: "Dizzy (chóng mặt)." },
            { id: 9, question: "In case of emergency, assume the ______ position.", options: ["A. hold", "B. brace", "C. duck", "D. down"], correctIndex: 1, explanation: "Brace position (tư thế ôm đầu cúi thấp)." },
            { id: 10, question: "Do not ______ your seatbelt until the captain turns off the sign.", options: ["A. undo", "B. unfasten", "C. unlock", "D. open"], correctIndex: 1, explanation: "Unfasten seatbelt (tháo dây an toàn)." },
            { id: 11, sectionTitle: "PART 2 – READING COMPREHENSION", passageTitle: "First Aid", passageContent: "If a passenger appears unconscious, check for breathing and a pulse immediately. Inform the cockpit crew and ask if there is a doctor on board.", question: "What is the first step for an unconscious passenger?", options: ["A. Call a doctor", "B. Give water", "C. Check breathing and pulse", "D. Move to business class"], correctIndex: 2, explanation: "Check breathing and pulse." },
            { id: 12, passageTitle: "First Aid", passageContent: "Inform the cockpit crew and ask if there is a doctor on board. Do not move the passenger unless in immediate danger.", question: "When should you move the passenger?", options: ["A. Immediately", "B. If they ask", "C. Only if in immediate danger", "D. Never"], correctIndex: 2, explanation: "Only if in immediate danger." },
            { id: 13, passageTitle: "Turbulence", passageContent: "We are experiencing some turbulence. Please return to your seats and fasten your seatbelts immediately.", question: "What should passengers do during turbulence?", options: ["A. Stand up", "B. Go to the toilet", "C. Sit down and fasten seatbelt", "D. Open overhead bin"], correctIndex: 2, explanation: "Sit down and fasten seatbelt." },
            { id: 14, passageTitle: "Emergency Exits", passageContent: "Emergency exits are equipped with slides that can be used as rafts in a water landing.", question: "What are slides used for in water?", options: ["A. Slides", "B. Beds", "C. Rafts", "D. Bridges"], correctIndex: 2, explanation: "Rafts (bè cứu sinh)." },
            { id: 15, passageTitle: "Smoking", passageContent: "Tampering with smoke detectors in the lavatory is a criminal offense.", question: "What is illegal according to the text?", options: ["A. Using the lavatory", "B. Smoking", "C. Tampering with smoke detectors", "D. Locking the door"], correctIndex: 2, explanation: "Tampering with smoke detectors." },
            { id: 16, sectionTitle: "PART 3 – GRAMMAR", question: "You ______ smoke in the lavatory.", options: ["A. must not", "B. don't have to", "C. needn't", "D. haven't"], correctIndex: 0, explanation: "Must not (cấm tuyệt đối)." },
            { id: 17, question: "If the pressure drops, masks ______ automatically.", options: ["A. appear", "B. will appear", "C. appeared", "D. appearing"], correctIndex: 1, explanation: "Will appear (câu điều kiện loại 1)." },
            { id: 18, question: "The crew ______ trained to handle medical emergencies.", options: ["A. is", "B. are", "C. has", "D. have"], correctIndex: 1, explanation: "The crew (tập hợp nhiều người) are trained." },
            { id: 19, question: "Have you ______ the safety demonstration?", options: ["A. watch", "B. watched", "C. watching", "D. watches"], correctIndex: 1, explanation: "Have watched (Hiện tại hoàn thành)." },
            { id: 20, question: "It is essential that every passenger ______ calm.", options: ["A. remains", "B. remain", "C. remaining", "D. remained"], correctIndex: 1, explanation: "Subjunctive mode: Essential that... remain (nguyên mẫu)." },
            { id: 21, sectionTitle: "PART 4 – VOCABULARY", question: "The First Aid ______ is located in the galley.", options: ["A. Box", "B. Kit", "C. Bag", "D. Set"], correctIndex: 1, explanation: "First Aid Kit (Bộ sơ cứu)." },
            { id: 22, question: "Please ______ the aisle immediately.", options: ["A. clear", "B. clean", "C. empty", "D. free"], correctIndex: 0, explanation: "Clear the aisle (giải tỏa lối đi)." },
            { id: 23, question: "There is a fire in the ______ oven.", options: ["A. rear", "B. back", "C. behind", "D. tail"], correctIndex: 0, explanation: "Rear oven (lò phía sau đuôi)." },
            { id: 24, question: "The captain has turned on the ______ seatbelt sign.", options: ["A. fast", "B. fasten", "C. fastening", "D. fastener"], correctIndex: 1, explanation: "Fasten seatbelt sign." },
            { id: 25, question: "CPR stands for Cardiopulmonary ______.", options: ["A. Rescue", "B. Resuscitation", "C. Recovery", "D. Return"], correctIndex: 1, explanation: "Resuscitation (Hồi sức tim phổi)." }
        ]
    },
    {
        id: 5,
        title: "TEST 5: CREW LIFE & CULTURE",
        description: "Chủ đề văn hóa, lịch bay, grooming và giao tiếp đồng nghiệp.",
        timeLimit: 25 * 60,
        questions: [
            { id: 1, sectionTitle: "PART 1 – SENTENCE COMPLETION", question: "Cabin crew are required to maintain high standards of ______.", options: ["A. dressing", "B. grooming", "C. wearing", "D. look"], correctIndex: 1, explanation: "Grooming (chăm chút ngoại hình)." },
            { id: 2, question: "I have a 24-hour ______ in Paris.", options: ["A. stop", "B. break", "C. layover", "D. stay"], correctIndex: 2, explanation: "Layover (nghỉ giữa chuyến)." },
            { id: 3, question: "Crew must report for ______ briefing 90 minutes before departure.", options: ["A. pre-flight", "B. before-flight", "C. early-flight", "D. past-flight"], correctIndex: 0, explanation: "Pre-flight briefing." },
            { id: 4, question: "The ______ indicates the schedule of flights for the month.", options: ["A. calendar", "B. roster", "C. diary", "D. plan"], correctIndex: 1, explanation: "Roster (lịch bay)." },
            { id: 5, question: "Crew members usually suffer from ______ after long-haul flights.", options: ["A. jet lag", "B. time zone", "C. sleeping", "D. tired"], correctIndex: 0, explanation: "Jet lag (lệch múi giờ)." },
            { id: 6, question: "You should always address passengers ______.", options: ["A. polite", "B. politeness", "C. politely", "D. politics"], correctIndex: 2, explanation: "Politely (trạng từ)." },
            { id: 7, question: "Senior crew members are expected to ______ junior staff.", options: ["A. mentor", "B. teacher", "C. learning", "D. study"], correctIndex: 0, explanation: "Mentor (hướng dẫn)." },
            { id: 8, question: "The captain gave a briefing on the expected weather ______.", options: ["A. conditions", "B. situation", "C. state", "D. way"], correctIndex: 0, explanation: "Weather conditions." },
            { id: 9, question: "Effective ______ is the key to a safe flight.", options: ["A. talk", "B. speech", "C. communication", "D. say"], correctIndex: 2, explanation: "Communication (giao tiếp)." },
            { id: 10, question: "The Purser is the ______ cabin crew member on board.", options: ["A. chief", "B. senior", "C. head", "D. top"], correctIndex: 1, explanation: "Senior cabin crew member (hoặc Senior Flight Purser)." },
            { id: 11, sectionTitle: "PART 2 – READING COMPREHENSION", passageTitle: "Teamwork", passageContent: "Emirates crew come from over 130 countries. It is essential to respect cultural differences and work together.", question: "What is essential for the crew?", options: ["A. Speaking 5 languages", "B. Respecting cultural differences", "C. Living in Dubai", "D. Flying everyday"], correctIndex: 1, explanation: "Respecting cultural differences." },
            { id: 12, passageTitle: "Uniform Standards", passageContent: "The uniform must be worn perfectly at all times. Hats are mandatory during boarding and disembarkation.", question: "When are hats mandatory?", options: ["A. During the flight", "B. During meal service", "C. During boarding and disembarkation", "D. When sleeping"], correctIndex: 2, explanation: "During boarding and disembarkation." },
            { id: 13, passageTitle: "Seniority", passageContent: "Promotions are based on performance and seniority. The sequence is from Grade 2 to Grade 1, then Purser.", question: "What is the rank after Grade 1?", options: ["A. Grade 2", "B. Captain", "C. Purser", "D. Manager"], correctIndex: 2, explanation: "Purser." },
            { id: 14, passageTitle: "Rest Periods", passageContent: "For flights over 14 hours, crew are entitled to a rest period in the crew rest compartment bunks.", question: "Where do crew rest on long flights?", options: ["A. Business class seats", "B. Jump seats", "C. Crew rest compartment bunks", "D. Cockpit"], correctIndex: 2, explanation: "Crew rest compartment bunks." },
            { id: 15, passageTitle: "Training", passageContent: "Recurrent training is conducted annually to ensure all crew are up to date with safety procedures.", question: "How often is recurrent training?", options: ["A. Monthly", "B. Annually", "C. Every 2 years", "D. Every 6 months"], correctIndex: 1, explanation: "Annually (hàng năm)." },
            { id: 16, sectionTitle: "PART 3 – GRAMMAR", question: "I have ______ for Emirates for 5 years.", options: ["A. work", "B. worked", "C. working", "D. works"], correctIndex: 1, explanation: "Have worked (Hiện tại hoàn thành)." },
            { id: 17, question: "She is ______ than him at handling difficult customers.", options: ["A. good", "B. better", "C. best", "D. well"], correctIndex: 1, explanation: "Better (so sánh hơn)." },
            { id: 18, question: "We look forward to ______ you to our team.", options: ["A. welcome", "B. welcoming", "C. welcomed", "D. welcomes"], correctIndex: 1, explanation: "Look forward to welcoming." },
            { id: 19, question: "While I ______ the passengers, the pilot called.", options: ["A. served", "B. was serving", "C. am serving", "D. serve"], correctIndex: 1, explanation: "Was serving (hành động đang diễn ra trong quá khứ)." },
            { id: 20, question: "Every crew member ______ responsible for safety.", options: ["A. is", "B. are", "C. be", "D. have"], correctIndex: 0, explanation: "Every... is (chia số ít)." },
            { id: 21, sectionTitle: "PART 4 – VOCABULARY", question: "Please sign the ______ sheet before leaving.", options: ["A. attendance", "B. attending", "C. attendant", "D. attend"], correctIndex: 0, explanation: "Attendance sheet (bảng điểm danh)." },
            { id: 22, question: "My ______ allowance is paid in local currency.", options: ["A. layover", "B. stay", "C. stop", "D. night"], correctIndex: 0, explanation: "Layover allowance (tiền phụ cấp khi nghỉ lại)." },
            { id: 23, question: "The ______ holds the briefing before the flight.", options: ["A. Purser", "B. Pilot", "C. Agent", "D. Staff"], correctIndex: 0, explanation: "Purser (Tiếp viên trưởng)." },
            { id: 24, question: "Always wear your ID ______ while on duty.", options: ["A. rope", "B. lanyard", "C. string", "D. chain"], correctIndex: 1, explanation: "Lanyard (dây đeo thẻ)." },
            { id: 25, question: "Red lipstick is a ______ part of the Emirates look.", options: ["A. signature", "B. sign", "C. signal", "D. signing"], correctIndex: 0, explanation: "Signature (đặc trưng)." }
        ]
    }
];

export default TEST_DB;
